version: 0.2

env:
  parameter-store:
    clientToOnboardConfig: "clientToOnboardConfig"

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - npm ci
      - npm i -g cdk
      - cdk deploy --require-approval=never
      - cat cdk.context.json
